version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-simple
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: orders
    command: mongod --bind_ip_all

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-simple
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
